### PR TITLE
Resolve publish issues in MySQL

### LINKED ISSUE #32: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value
I started testing out now after fixing database creation for **MySQL**. So, error show up when publish data:

```bash
Type: PDOException
Code: 22007
Message: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2018-10-19T21:18:39+00:00' for column 'created' at row 1
File: /home/vagrant/code/my-chronicle/vendor/paragonie/easydb/src/EasyDB.php
Line: 846
Trace: #0 /home/vagrant/code/my-chronicle/vendor/paragonie/easydb/src/EasyDB.php(846): PDOStatement->execute(Array)
#1 /home/vagrant/code/my-chronicle/vendor/paragonie/easydb/src/EasyDB.php(521): ParagonIE\EasyDB\EasyDB->safeQuery('INSERT INTO `ch...', Array, 4, true)
#2 /home/vagrant/code/my-chronicle/src/Chronicle/Chronicle.php(114): ParagonIE\EasyDB\EasyDB->insert('chronicle_chain', Array)
#3 /home/vagrant/code/my-chronicle/src/Chronicle/Handlers/Publish.php(92): ParagonIE\Chronicle\Chronicle::extendBlakechain('{\n    "date": "...', 'w8J2tTFL5THh4P_...', Object(ParagonIE\Sapient\CryptographyKeys\SigningPublicKey))
#4 [internal function]: ParagonIE\Chronicle\Handlers\Publish->__invoke(Object(Slim\Http\Request), Ob" while reading response header from upstream, client: 192.168.10.1, server: chronicle.local, request: "POST /chronicle/publish HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "chronicle.local"
```
More investigation will going on tomorrow morning, if God's will. ^_^

### PR DESCRIPTION
**Pull request by vzool**
also fixes #32 😘

### CODE REVIEW

**Comment by paragonie-scott** [comment]
By the way, you can just use `$db->getDriver()` instead of parsing out the DSN.

**Comment by vzool** [comment]
Aha okey 😃

**Comment by vzool** [comment]
> By the way, you can just use `$db->getDriver()` instead of parsing out the DSN.

Done 😋

**Comment by vzool** [comment]
I love green signs 😍 Do you prefer to make all these modifications in one commit? 🙃

**Comment by paragonie-scott** [comment]
Wait, how'd you get the tests to pass with the `void` return type? That seems off.

**Comment by vzool** [comment]
> Wait, how'd you get the tests to pass with the `void` return type? That seems off.

Yes, of course. This is odd for PHP realm.
But, it is totally fine for C/C++ realm.
Because, I'm a C/C++ developer from the beginning then I became a PHP developer and when tests complaints about the return types, I'm a very aware of `return types` and `casting`. So, I search for what is available for PHP.

Finally, I found it [here](http://php.net/manual/en/migration71.new-features.php) which is clear that PHP is supporting `void` as a return type.

Thanks for asking ^_^

**Comment by vzool** [comment]
> Wait, how'd you get the tests to pass with the `void` return type? That seems off.

Yes, of course. This is odd for PHP realm.
But, it is totally fine for C/C++ realm.
Because, I'm a C/C++ developer from the beginning then I became a PHP developer and when tests complaints about the return types, I'm a very aware of `return types` and `casting`. So, I search for what is available for PHP.

Finally, I found it [here](http://php.net/manual/en/migration71.new-features.php) which is clear that PHP is supporting `void` as a return type.

Thanks for asking ^_^

**Comment by vzool** [comment]
> Wait, how'd you get the tests to pass with the `void` return type? That seems off.

Yes, of course. This is odd for PHP realm.
But, it is totally fine for C/C++ realm.
Because, I'm a C/C++ developer from the beginning then I became a PHP developer and when tests complaints about the return types, I'm a very aware of `return types` and `casting`. So, I search for what is available for PHP.

Finally, I found it [here](http://php.net/manual/en/migration71.new-features.php) which is clear that PHP is supporting `void` as a return type.

Thanks for asking ^_^

**Comment by vzool** [comment]
Yes, of course. This is odd for PHP realm.
But, it is totally fone for C/C++ realm.
Because, I'm a C/C++ developer from the beginning then I became a PHP
developer and when tests complaints about the return types, I'm a very
aware of `return types` and `casting`. So, I search for what is available
for PHP.

Finally, I found it [here](
http://php.net/manual/en/migration71.new-features.php) which is clear that
PHP is supporting `void` as a return type.

Thanks for asking ^_^

**Comment by paragonie-scott** [comment]
Sorry for being unclear: The problem is that Chronicle supports PHP 7.0 and the `void` return type didn't land until 7.1.

**Comment by vzool** [comment]
Aha, maybe it was there since 7.0 but not documented until 7.1 🤔

**Comment by paragonie-scott** [comment]
Nope. I think it's treating it like a class return hint. Interesting.

**Comment by paragonie-scott** [comment]
I'll remove the type hint but keep the docblock. Thanks a lot! :)

**Comment by vzool** [comment]
You're welcome, I'm still looking for types directory at php-src 😆

**Pull request merged**
