### PR TITLE
Add redirection to public directory if Chronicle is installed at public_html in any Shared Hosting

### PR DESCRIPTION
**Pull request by vzool**

### CODE REVIEW

**Comment by paragonie-scott** [comment]
This is an antipattern. You should never expose the contents of the directories outside `public` to the document root. Otherwise, attackers can just go to `/local/settings.json` or `/local/client.key` and steal your signing keys.

**Instead**: Chronicle shouldn't be deployed on shared hosting platforms where the end user cannot specify a different path for a virutal host to prevent this sort of access.

**Comment by vzool** [comment]
Yes, your right! But shared hosting is easy to manage for many people and they are everywhere, as myself I have a shared hosting with root access while many people don't.

**Comment by vzool** [comment]
What about protecting `local` directory with `htaccess` ^_^

**Comment by vzool** [comment]
OK, it is a bad idea at all levels. Ha ha ha

**Pull request closed without merging**
